grafana:
  enabled: true

  readinessProbe:
    httpGet:
      path: /api/health
      port: grafana
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30

  livenessProbe:
    httpGet:
      path: /api/health
      port: grafana
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 30
    failureThreshold: 10

  startupProbe:
    httpGet:
      path: /api/health
      port: grafana
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
