name: Kubernetes Platform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm lint
        run: helm lint helm/platform-api

      - name: Helm template
        run: |
          helm template platform-api helm/platform-api \
            --namespace platform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: terraform
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: terraform
        run: terraform validate

      - name: Build container
        run: docker build -t platform-api:ci app
